# black-list-secret-scan: []
branch: master
# check:
# - CKV_DOCKER_1
# compact: true
# directory:
# - .
# docker-image: sample-image
# dockerfile-path: Dockerfile
# download-external-modules: true
# evaluate-variables: true
# external-checks-dir:
# - sample-dir
# external-modules-download-path: .external_modules
framework:
- all
# no-guide: true
# quiet: true
# repo-id: bridgecrew/sample-repo
# secrets-scan-file-type: []
skip-check:
- CKV_DOCKER_3
- CKV_DOCKER_2
# skip-fixes: true
skip-framework:
- terraform_plan
# - dockerfile
# - secrets
# skip-suppressions: true
# soft-fail: true
