coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Fail the status if coverage drops by >= 1%
        threshold: "1"
    patch:
      default:
        # Fail the status if coverage drops by >= 1%
        threshold: "1"

codecov:
  token: b83acabe-5242-47bd-b085-3d01118049da