language: node_js

os: linux
dist: bionic
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable

services:
  - xvfb

node_js:
  - node

# before_install:
#   - pip install selenium
#   - pip install --user codecov

install:
  - snyk auth $SNYK_TOKEN
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser

script:
  - npm test
  - npm run e2e

# after_success:
#   - codecov
