language: node_js

os: linux
dist: bionic
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - xvfb

node_js:
  - node

before_install:
  - npm install -g snyk
  - snyk auth $SNYK_TOKEN

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - pip install selenium
#   - pip install --user codecov

script:
  - npm test
  - npm run e2e

# after_success:
#   - codecov
