language: node_js

os: linux
dist: bionic
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - xvfb

node_js:
  - node

before_script:
  - export CHROME_BIN=chromium-browser
  # - pip install selenium

script:
  - npm run PIPELINE
