language: node_js

os: linux
virt: lxd

# os: linux
# dist: focal 
# virt: vm

group: edge
arch: arm64-graviton2

addons:
  chrome: stable

cache: false

services:
  - xvfb

node_js:
  - node

before_script:
  - export CHROME_BIN=google-chrome
  # - pip install selenium

script:
  - npm run build
