language: 
  node_js

node_js:
  - 'lts/*'

before_install:
  - pip install --user codecov

before_script:
  - 'export CHROME_BIN=chromium-browser'
  - # removed: xenial dist breaking change fix: 'export DISPLAY=:99.0'
  - # removed: xenial dist breaking change fix: 'sh -e /etc/init.d/xvfb start'

services:
 - xvfb

scripts:
  - npm install codecov -g

after_success:
  - codecov
