language: 
  node_js

os:
  - 'linux'

dist: xenial

services:
  - xvfb

node_js:
  - 'node'

before_install:
  - pip install --user codecov

before_script:
  - 'export CHROME_BIN=chromium-browser'

script:
  - npm install codecov -g

after_success:
  - codecov
