version: 0.7.0.{build}

branches:
  only:
    - master

image: Ubuntu2004

environment:
  matrix:
  - nodejs_version: "14.3.0"
  custom_appveyor: yes

matrix:
  fast_finish: true

install:
  - nvm list
  - ps: nvm use (Get-Content -Raw -Path package.json | ConvertFrom-Json).engines.node
  - node --version
  - npm --version
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version.$env:APPVEYOR_BUILD_NUMBER"
  - npm install

test_script:
  - npm test

build: off
