environment:
  matrix:
  - nodejs_version: "8.11.2"
  custom_appveyor: yes

matrix:
  fast_finish: true

install:
  - npm install

test_script:
  - node --version && npm --version
  - npm test

build: off
