environment:
  matrix:
  - nodejs_version: "8.11.2"

matrix:
  fast_finish: true

install:
  - npm install

test_script:
  - node --version
  - npm test

build: off

environment:
  custom_appveyor: yes