version: 0.7.0.{build}

branches:
  only:
    - master

image: Visual Studio 2019

environment:
  matrix:
  - nodejs_version: "14.3.0"
  custom_appveyor: yes

matrix:
  fast_finish: true

install:
  - ps: $env:package_node_version = Get-Content package.json | ConvertFrom-Json | Select -ExpandProperty engines | Select -ExpandProperty node
  - ps: $env:package_node_version
  - ps: $env:package_npm_version = Get-Content package.json | ConvertFrom-Json | Select -ExpandProperty engines | Select -ExpandProperty npm
  - ps: $env:package_npm_version
  - nvm install $env:package_node_version
  - nvm use $env:package_node_version
  - nvm list
  - node --version
  - npm --version
  - ps: $env:package_version = Get-Content package.json | ConvertFrom-Json | Select -ExpandProperty version
  - ps: Update-AppveyorBuild -Version "$env:package_version.$env:APPVEYOR_BUILD_NUMBER"
  - npm install -g snyk
  - snyk auth $SNYK_TOKEN
  - npm install

test_script:
  - npm test

build: off
