version: 0.2.{build}

branches:
  only:
    - master

environment:
  matrix:
  - nodejs_version: "8.11.2"
  custom_appveyor: yes

matrix:
  fast_finish: true

install:
  - cmd: "PowerShell $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-JSON).version"
  - echo %$env:package_version%
  - Update-AppveyorBuild -Version \"$($env.package_version)\"
  - npm install

test_script:
  - node --version && npm --version
  - npm test

build: off
