#!/bin/bash

# echo $'\033[1;33m'Running script launcher
# echo ------------------------------------------------------
# echo

# echo Command launcher time tracker starting...$'\033[0m'
# pwd=$(pwd)
# pwd
# ls -F --color=always
# echo


export JORICH_LAUNCHER_COUNTER=$(($JORICH_LAUNCHER_COUNTER+1))
echo ${JORICH_LAUNCHER_COUNTER} >/tmp/JORICH_LAUNCHER_COUNTER

    prompt=$(printf "%"$JORICH_LAUNCHER_COUNTER"s" | tr " " "]")

    date=$(echo "$(tput setaf 4)$(date --rfc-3339='ns')$(tput sgr 0)")
    printf "%s %s " $prompt $date && \
    printf "\n" && \

    TIMEFORMAT=$'\033[34mreal: \033[36m%3lR\033[34m    user: %3lU    sys: %3lS    CPU: %P%%\033[0m' && \
    time ( eval $1 && printf "%s"" " $prompt) && \

read JORICH_LAUNCHER_COUNTER </tmp/JORICH_LAUNCHER_COUNTER
export JORICH_LAUNCHER_COUNTER=$(($JORICH_LAUNCHER_COUNTER-1))


# echo $'\033[0;33m'Command launcher time tracker finished...$'\033[0m'

# echo
# # read  -n 1 -p "x" input
# # exit