global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus-remote
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  static_configs:
  - targets:
    - cv-generator-fe.herokuapp.com:9090
    labels:
      group: 'production'
- job_name: cv-generator-remote
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  static_configs:
  - targets:
    - cv-generator-fe.herokuapp.com:5000
    labels:
      group: 'production'
- job_name: prometheus-local
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 3s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    labels:
      group: 'staging'
- job_name: cv-generator-local
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 3s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:5000
    labels:
      group: 'staging'
- job_name: node
  static_configs:
  - targets:
    - localhost:9090
    labels:
      group: 'staging'
