global:
  scrape_interval: 1m # default = 1m
  scrape_timeout: 60s # default = 10s
  evaluation_interval: 1m # default = 1m
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
  - static_configs:
    - targets: []
    scheme: https
    timeout: 10s
scrape_configs:
- job_name: cv-generator-remote
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - cv-generator-fe.herokuapp.com
    labels:
      group: 'production'
- job_name: cv-generator-remote-eu
  scrape_interval: 15s # default = 1m
  scrape_timeout: 10s # default = 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - cv-generator-fe-eu.herokuapp.com
    labels:
      group: 'production-eu'
- job_name: cv-generator-local
  scrape_interval: 2s # default = 1m
  scrape_timeout: 1s # default = 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    labels:
      group: 'staging'
