version: 2.1
orbs:
  node: circleci/node@7.2.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm install
      - save_cache:
          paths:
            - ~/.npm
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run: npm test
  run-pipeline:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm install
      - save_cache:
          paths:
            - ~/.npm
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run: npm run build
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - run-pipeline
